# 【注意】
# 1. “#”符号表示注释，被注释掉的配置是【不会生效】，如果想让其生效，请去掉它
# 2. 请确保格式正确，否则会报错（只需要删除一个符号即可，其他的空格不用删除）
# 3. 实在不理解的可以前往 https://t.me/+A6PlLqiqK19mNzNl 问一问其他已了解的伙伴
# 4. 标注了“可单独配置”的，皆可以在对应的账号下添加，优先级更高

# 【选填】 全局延迟配置（可单独配置，直接在对应的账号中添加相同的格式即可）
# 功能描述：完成阅读，获取阅读文章前的睡眠时间
delay:
  # 模拟阅读时间，默认随机 11-16
  # Tips： 最小不能低于8秒（网络传输有延迟，最好高一点，也可以按照默认的不改动）
  read_delay:
    - 11
    - 16

# 【选填】 最大线程数，默认为 1
# 功能描述：设置线程池的最大线程数，每个线程可以单独跑一个账号
#max_thread_count: 1

# 【必填】
account_data:
  # 账号名（自定义）
  账号1:
    #【必填】
    authorization: "auth_1"

#  账号2:
#    authorization: "auth_2"
#  账号3:
#    authorization: "auth_3"